const express = require('express')
const path = require('path')
const hbs =  require('hbs')

const app = express()

// Path manipulation
//console.log(__dirname)
//console.log(__filename)
//console.log(path.join(__dirname, '../public'))

// Define path for express config
const staticSource = path.join(__dirname, '../public')
const viewsPath = path.join(__dirname, '../templates/views')
const partialsPath = path.join(__dirname, '../templates/partials')

// Setur handlebars engine (Dynamic content)
app.set('view engine', 'hbs')

// Custom location to the hbs files (Default is 'views')
app.set('views', viewsPath)

// Partials location (nodemon src/app.js -e, for restart the server when partials changes)
hbs.registerPartials(partialsPath)

// Setup static directory to serve
app.use(express.static(staticSource))

// Handlebar
app.get('', (req, res) => {
    res.render('index', {
        title: 'Cats!',
        value: 5.000,
        cat: 'Cat'
    })
})
app.get('/dogs', (req, res) => {
    res.render('dogs', {
        title: 'Dogs!',
        value: 5.000
    })
})
app.get('/products', (req, res) => {
    // Object generated by query strings (http://localhost:3000/products?fil=3&stat=5 -> { fil: 3, stat: 5 })
    //console.log(req.query)
    res.send({
        products: []
    })
})

// Direct html
app.get('/html', (req, res) => {
    res.send('<h1>Pure html tags!</h1>')
})

app.get('/html/*', (req, res) => {
    res.send('<h1>Big paths!</h1>')
})

app.get('*', (req, res) => {
    res.send('<h1>404 bro!</h1>')
})

app.listen(3000, () => {
    console.log('Server is up on port 3000.')
})